-- ============================================================================
-- LearnInText 云数据库一键初始化（全量基线）
-- ============================================================================
-- 用途：全新 Supabase 项目只需在 Dashboard → SQL Editor 执行本文件一次，
--       等价于按顺序执行 migrations/0001 ~ 0012 的最终累积状态。
-- 幂等：可重复执行，不会删除已有数据；在已按迁移链初始化过的库上执行也安全
--       （会顺带完成收尾：profiles 开启 RLS、回收 anon 全部表权限、
--        删除注册专用 RPC 并收紧 security definer 函数授权）。
-- 注意：本文件是全量基线，供人工执行；请勿移入 migrations/ 目录，
--       以免未来用 CLI 管理迁移时被当作增量脚本重复执行。
-- 与迁移链的差异（均为修复/收紧，不影响功能）：
--   * 显式 alter table public.profiles enable row level security（原迁移链缺失，
--     导致 profiles 上的策略不生效，存在匿名读取用户名/邮箱的风险）
--   * 业务表权限仅授予 authenticated，并回收 anon（匿名不保留任何表权限与 RPC）
--   * 对齐 0012：登录收紧为「邮箱直登」——注册已下线，账号由管理员在控制台
--     手动创建；删除注册专用 RPC username_exists 与 resolve_login_identifier
--     （后者曾允许匿名调用者按用户名换取任意用户邮箱），set_username /
--     auth_username 仅 authenticated 可执行
-- ⚠️ 部署后需在 Dashboard → Authentication → Providers → Email 关闭
--    「Enable Email Signup」，否则 API 层仍可直接调 /auth/v1/signup 注册。
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 业务表（列名使用 camelCase 双引号，与前端 sync.js 的字段名严格一致；
--    0002 软删除列 / 0007 排序列 / 0008 描述列 / 0009 uid 列已并入建表语句）
-- ----------------------------------------------------------------------------
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  username text not null,
  title text not null default '',
  content text not null default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "deletedAt" timestamptz,
  "sortOrder" double precision,
  "description" text not null default '',
  "uid" text
);

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  username text not null,
  word text not null,
  "articleId" bigint not null,
  definitions jsonb not null default '[]',
  examples jsonb not null default '[]',
  source text not null default '',
  "updatedAt" timestamptz not null default now(),
  "deletedAt" timestamptz
);

create table if not exists public.word_marks (
  id bigint generated by default as identity primary key,
  username text not null,
  "articleId" bigint not null,
  "wordId" bigint not null,
  "occKey" text not null default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "deletedAt" timestamptz
);

create table if not exists public.context_translations (
  id bigint generated by default as identity primary key,
  username text not null,
  "wordId" bigint not null,
  "articleId" bigint not null,
  "occKey" text not null default '',
  translation text not null default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "deletedAt" timestamptz
);

-- 用户资料表：username 唯一绑定 auth.users.id
-- username 唯一性由下方部分唯一索引保证（'' 行不参与），避免多个
-- 未绑定用户名的注册因 '' 重复而 unique 违约
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default '',
  email text not null default '',
  "createdAt" timestamptz not null default now()
);

-- 设置同步表：每个 username 一行，settings 为整块 JSON，updatedAt 供 LWW 冲突解决
create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  username text unique not null,
  settings jsonb not null default '{}',
  "updatedAt" timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2. 索引
-- ----------------------------------------------------------------------------
create index if not exists idx_articles_username on public.articles (username);
create index if not exists idx_articles_username_uid on public.articles (username, "uid");
create index if not exists idx_words_username_word on public.words (username, word);
create index if not exists idx_words_username_article on public.words (username, "articleId");
create index if not exists idx_word_marks_username_article on public.word_marks (username, "articleId");
create index if not exists idx_word_marks_username_word on public.word_marks (username, "wordId");
create index if not exists idx_context_translations_username_article on public.context_translations (username, "articleId");
-- username 部分唯一索引：空 username（未绑定）行不参与唯一约束
create unique index if not exists profiles_username_unique
  on public.profiles (username)
  where username <> '';
-- email 部分唯一索引：空 email 不参与唯一约束（兼容未确认邮箱的注册流程）
create unique index if not exists profiles_email_unique
  on public.profiles (email)
  where email <> '';

-- ----------------------------------------------------------------------------
-- 3. RPC 函数（迁移链最终版 + 0012 收紧：注册专用 RPC 已删除）
-- ----------------------------------------------------------------------------
-- 当前登录用户（auth.uid()）在 profiles 中绑定的 username，供 RLS 策略调用
create or replace function public.auth_username()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select username
  from public.profiles
  where id = auth.uid();
$$;

-- 注册触发器：auth.users 创建用户时（含控制台手动建号）自动建 profile，
-- 从 meta 写入用户名（手动建号无 meta，落库为 ''，由首次登录绑定补齐）；
-- 含服务端格式校验与撞名检查（0010 加固版）
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  meta_username text := nullif(new.raw_user_meta_data ->> 'username', '');
begin
  -- 服务端格式校验：非法 username 按 null 处理（落库为 ''）
  if meta_username is not null and meta_username !~ '^[A-Za-z0-9_]{3,20}$' then
    meta_username := null;
  end if;

  -- 撞名检查：抛出契约错误码，供前端映射为「该用户名已被占用」
  if meta_username is not null
     and exists (select 1 from public.profiles where username = meta_username) then
    raise exception 'username_already_taken';
  end if;

  insert into public.profiles (id, email, username)
  values (new.id, coalesce(new.email, ''), coalesce(meta_username, ''))
  on conflict (id) do update
    set email = excluded.email,
        username = case
          -- 已绑定过业务用户名则不覆盖，避免误改
          when public.profiles.username = '' then excluded.username
          else public.profiles.username
        end;
  return new;
end;
$$;

-- username 一旦设置即不可修改（'' -> 值 允许，其余一律拒绝）
create or replace function public.prevent_username_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.username <> '' and new.username is distinct from old.username then
    raise exception 'username_immutable';
  end if;
  return new;
end;
$$;

-- 设置用户名：手动创建的账号首次登录时由客户端调用绑定（仅当前为空时允许；
-- 服务端格式校验，username 唯一部分唯一索引兜底撞名）；成功返回 true
drop function if exists public.set_username(text);
create or replace function public.set_username(uname text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  cur_username text;
begin
  select username into cur_username
  from public.profiles
  where id = auth.uid();

  if cur_username is null then
    raise exception 'profile_not_found';
  end if;

  if cur_username <> '' then
    raise exception 'username_immutable';
  end if;

  if uname is null or uname !~ '^[A-Za-z0-9_]{3,20}$' then
    raise exception 'invalid_username_format';
  end if;

  update public.profiles
  set username = uname
  where id = auth.uid();

  return true;
end;
$$;

-- 注册已下线（账号由管理员手动创建，登录为邮箱直登）：
-- 删除注册专用 RPC —— username_exists（注册预检）与
-- resolve_login_identifier（用户名→邮箱解析，曾允许匿名调用者换取任意用户邮箱）。
-- drop 语句使「在存量库上重放本基线」也能一并清除这两个已废弃函数。
drop function if exists public.resolve_login_identifier(text);
drop function if exists public.username_exists(text);

-- ----------------------------------------------------------------------------
-- 4. 触发器
-- ----------------------------------------------------------------------------
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists profiles_username_immutable on public.profiles;
create trigger profiles_username_immutable
  before update on public.profiles
  for each row execute function public.prevent_username_change();

-- ----------------------------------------------------------------------------
-- 5. RLS：业务表（0010 最终版，(select ...) 包裹使函数每语句仅评估一次）
-- ----------------------------------------------------------------------------
alter table public.articles enable row level security;
drop policy if exists auth_user_access on public.articles;
create policy auth_user_access on public.articles
  for all to authenticated
  using (username = (select public.auth_username()))
  with check (username = (select public.auth_username()));

alter table public.words enable row level security;
drop policy if exists auth_user_access on public.words;
create policy auth_user_access on public.words
  for all to authenticated
  using (username = (select public.auth_username()))
  with check (username = (select public.auth_username()));

alter table public.word_marks enable row level security;
drop policy if exists auth_user_access on public.word_marks;
create policy auth_user_access on public.word_marks
  for all to authenticated
  using (username = (select public.auth_username()))
  with check (username = (select public.auth_username()));

alter table public.context_translations enable row level security;
drop policy if exists auth_user_access on public.context_translations;
create policy auth_user_access on public.context_translations
  for all to authenticated
  using (username = (select public.auth_username()))
  with check (username = (select public.auth_username()));

alter table public.user_settings enable row level security;
drop policy if exists auth_user_access on public.user_settings;
create policy auth_user_access on public.user_settings
  for all to authenticated
  using (username = (select public.auth_username()))
  with check (username = (select public.auth_username()));

-- profiles：显式开启 RLS（修复点：原迁移链缺失此句，策略不生效）
alter table public.profiles enable row level security;
drop policy if exists "select own profile" on public.profiles;
create policy "select own profile" on public.profiles
  for select
  using ((select auth.uid()) = id);

-- 不再授予/定义 profiles 的 UPDATE 策略：authenticated 的 UPDATE 权限已收回
-- （0011），email 会被恶意抢占导致他人无法注册；email 的合法同步路径只有
-- handle_new_user 触发器（security definer），username 设置走 set_username RPC

-- 说明：tombstones 表目前仅存在于本地 Dexie，云端未建表；若未来云端建表，
-- 需参照上面对应补一条 auth_user_access 策略。

-- ----------------------------------------------------------------------------
-- 6. 权限（收紧版）：业务表仅 authenticated；匿名不保留任何表权限与 RPC
-- ----------------------------------------------------------------------------
grant select, insert, update, delete
  on public.articles, public.words, public.word_marks,
     public.context_translations, public.user_settings
  to authenticated;
-- profiles 仅授予 SELECT：UPDATE 已收回（0011），防止 authenticated
-- 恶意抢占他人 email；合法更新走 security definer 的触发器 / RPC，不受影响
grant select on public.profiles to authenticated;

grant usage, select on sequence public.articles_id_seq to authenticated;
grant usage, select on sequence public.words_id_seq to authenticated;
grant usage, select on sequence public.word_marks_id_seq to authenticated;
grant usage, select on sequence public.context_translations_id_seq to authenticated;
grant usage, select on sequence public.user_settings_id_seq to authenticated;

-- 防御性回收：Supabase 的默认授权会把新表权限也给 anon，这里显式收回
--（注册已下线，匿名不需要访问任何表；客户端表操作均以 authenticated 会话进行）
revoke select, insert, update, delete
  on public.articles, public.words, public.word_marks,
     public.context_translations, public.user_settings, public.profiles
  from anon;
revoke all
  on sequence public.articles_id_seq, public.words_id_seq,
     public.word_marks_id_seq, public.context_translations_id_seq,
     public.user_settings_id_seq
  from anon;

-- RPC 授权：匿名不保留任何 RPC；security definer 函数默认授权给 PUBLIC，
-- 必须显式收回，仅保留 authenticated 所需的两项（RLS 评估 / 首次绑定用户名）
revoke execute on function public.set_username(text) from public, anon;
grant execute on function public.set_username(text) to authenticated;

revoke execute on function public.auth_username() from public, anon;
grant execute on function public.auth_username() to authenticated;

-- 注册触发器函数仅 service_role 可执行（触发本身不需要 EXECUTE 权限，回收防裸调）
revoke execute on function public.handle_new_user() from public, anon, authenticated;
grant execute on function public.handle_new_user() to service_role;
