-- ============================================================================
-- LearnInText 云数据库初始化 / RLS 最小加固
-- ============================================================================
-- 执行方式：Supabase Dashboard → SQL Editor → New query → 粘贴本文件全部内容 → Run
-- 本迁移幂等，可重复执行；不会删除已有数据。
--
-- 安全模型（个人使用，最小加固）：
--   * 数据仍按 username 字段隔离（应用层约定）；
--   * 开启 RLS：请求必须携带请求头 x-sync-user，且其值必须与行的 username
--     一致，否则拒绝访问。
--   * 作用：挡住“拿到 anon key 后在浏览器/脚本中直接裸查”的意外泄露。
--     注意：x-sync-user 是自报身份，非强认证；多人共用云库时仍需谨慎。
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 业务表（列名使用 camelCase 双引号，与前端 sync.js 的字段名严格一致）
-- ----------------------------------------------------------------------------
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  username text not null,
  title text not null default '',
  content text not null default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  username text not null,
  word text not null,
  "articleId" bigint not null,
  definitions jsonb not null default '[]',
  examples jsonb not null default '[]',
  source text not null default '',
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.word_marks (
  id bigint generated by default as identity primary key,
  username text not null,
  "articleId" bigint not null,
  "wordId" bigint not null,
  "occKey" text not null default '',
  "createdAt" timestamptz not null default now()
);

create table if not exists public.context_translations (
  id bigint generated by default as identity primary key,
  username text not null,
  "wordId" bigint not null,
  "articleId" bigint not null,
  "occKey" text not null default '',
  translation text not null default '',
  "createdAt" timestamptz not null default now()
);

-- 常用查询索引
create index if not exists idx_articles_username on public.articles (username);
create index if not exists idx_words_username_word on public.words (username, word);
create index if not exists idx_words_username_article on public.words (username, "articleId");
create index if not exists idx_word_marks_username_article on public.word_marks (username, "articleId");
create index if not exists idx_word_marks_username_word on public.word_marks (username, "wordId");
create index if not exists idx_context_translations_username_article on public.context_translations (username, "articleId");

-- ----------------------------------------------------------------------------
-- 2. 读取请求头的辅助函数（RLS 策略中调用）
-- ----------------------------------------------------------------------------
create or replace function public.sync_user()
returns text
language sql
stable
as $$
  select nullif(current_setting('request.headers', true)::json->>'x-sync-user', '')
$$;

-- ----------------------------------------------------------------------------
-- 3. RLS：仅允许 x-sync-user 与行 username 一致的读写
-- ----------------------------------------------------------------------------
alter table public.articles enable row level security;
drop policy if exists "sync_user_access" on public.articles;
create policy "sync_user_access" on public.articles
  for all
  using (username = public.sync_user())
  with check (username = public.sync_user());

alter table public.words enable row level security;
drop policy if exists "sync_user_access" on public.words;
create policy "sync_user_access" on public.words
  for all
  using (username = public.sync_user())
  with check (username = public.sync_user());

alter table public.word_marks enable row level security;
drop policy if exists "sync_user_access" on public.word_marks;
create policy "sync_user_access" on public.word_marks
  for all
  using (username = public.sync_user())
  with check (username = public.sync_user());

alter table public.context_translations enable row level security;
drop policy if exists "sync_user_access" on public.context_translations;
create policy "sync_user_access" on public.context_translations
  for all
  using (username = public.sync_user())
  with check (username = public.sync_user());

-- ----------------------------------------------------------------------------
-- 4. 角色授权（anon 客户端需要的最小权限；实际数据访问由 RLS 把关）
-- ----------------------------------------------------------------------------
grant select, insert, update, delete
  on public.articles, public.words, public.word_marks, public.context_translations
  to anon;

grant usage, select on sequence public.articles_id_seq to anon;
grant usage, select on sequence public.words_id_seq to anon;
grant usage, select on sequence public.word_marks_id_seq to anon;
grant usage, select on sequence public.context_translations_id_seq to anon;

grant execute on function public.sync_user() to anon;
