-- ============================================================================
-- LearnInText 云数据库迁移 0004：设置同步表
-- ============================================================================
-- 背景：登录用户可跨设备同步「设置」内容（AI 供应商、主题、token 限制等）。
--   * 新增 user_settings 表：每个 username 一行，settings 为整个设置的 JSON，
--     updatedAt 用于 LWW（最近修改者胜出）冲突解决；
--   * RLS 强认证：行的 username 必须等于当前登录用户在 profiles 中的 username。
-- ============================================================================

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  username text unique not null,
  settings jsonb not null default '{}',
  "updatedAt" timestamptz not null default now()
);

create index if not exists idx_user_settings_username on public.user_settings (username);

-- 业务数据访问辅助（与业务表一致）：当前登录用户的 username
create or replace function public.auth_username()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select username
  from public.profiles
  where id = auth.uid();
$$;

alter table public.user_settings enable row level security;
drop policy if exists "auth_user_access" on public.user_settings;
create policy "auth_user_access" on public.user_settings
  for all
  using (username = public.auth_username())
  with check (username = public.auth_username());

grant select, insert, update, delete on public.user_settings to anon;
grant usage, select on sequence public.user_settings_id_seq to anon;
